title: Python Lambda Functions
hero_image: images/banner.png
subtitle: generic-python-lambda-functions subtitle
description: generic-python-lambda-functions description
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: cc-prototype
published: false
steps:
  - title: lambda functions

