title: Python Lambda Functions
hero_image: images/banner.png
description: Using Python's lambda function
original_url:
theme: cc-prototype
duration: 1
ingredient: true
listed: false
copyedit: true
interests:
technologies: "python"
steps:
  - title: lambda functions

